name: Deploy to Databricks

on:
  push:
    branches:
      - main

jobs:
  deploy-to-databricks:
    runs-on: ubuntu-latest
    # Name of the environment you created
    environment: Testt
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      # Install databricks CLI as per https://docs.databricks.com/dev-tools/cli/databricks-cli.html
      - name: Install databricks CLI
        run: |
         curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh

      # List the databricks repos within the workspace whose credentials
      # are stored in the Github Environment "my-environment"
      - name: List databricks repos
        env:
          # Note the host is an "environment variable" in the Github Environment
          # while the token is a "secret" in the Github Environment
          DATABRICKS_HOST: ${{ vars.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          databricks repos list
      - name: Copy files to Databricks workspace
        run: |
          databricks workspace mkdirs "/Workspace/Users/ahosny@orion360.com/Hsny" 
          
        env:
          DATABRICKS_HOST: ${{ vars.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
            
