name: Deploy to Databricks

on:
  push:
    branches:
      - main

jobs:
  deploy-to-databricks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install/Upgrade Databricks CLI
      run: |
        pip install --upgrade databricks-cli
          
    - name: Upgrade urllib3 and chardet
      run: pip install --upgrade urllib3==1.26.14 chardet==3.0.4


    - name: Configure Databricks CLI
      run: |
          echo "[DEFAULT]" > ~/.databricks-config
          echo "host = $DATABRICKS_HOST" >> ~/.databricks-config
          echo "token = $DATABRICKS_TOKEN" >> ~/.databricks-config
      shell: bash
      env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

   

    - name: Copy files to Databricks workspace
      run: |
        databricks workspace import_dir --overwrite . "/$DATABRICKS_FOLDER"
      env:
        DATABRICKS_WORKSPACE_PATH: ${{ secrets.DATABRICKS_FOLDER }}
