name: Deploy to Databricks

on:
  push:
    branches:
      - main

jobs:
  deploy-to-databricks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Databricks CLI
      run: pip install databricks-cli

    - name: Configure Databricks CLI
      run: |
        databricks configure --host "$DATABRICKS_HOST" --token "$DATABRICKS_TOKEN"
      env:
        DATABRICKS_HOST: ${{ vars.DATABRICKS_HOST }}
        DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

    - name: Copy files to Databricks workspace
      run: |
        databricks workspace import_dir --overwrite . "/$DATABRICKS_FOLDER"
      env:
        DATABRICKS_WORKSPACE_PATH: ${{ secrets.DATABRICKS_FOLDER }}
